# Netlify configuration for static site
[build]
  publish = "."
  command = ""
  functions = "netlify/functions"

[dev]
  framework = "#static"
  autoLaunch = false

# Basic security + caching headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), accelerometer=(), gyroscope=(), fullscreen=(self)"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob: https://*.supabase.co; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://*.supabase.co wss://*.supabase.co; frame-ancestors 'none'; base-uri 'self'; form-action 'self'"

# Pretty share URL -> Function with OG tags
[[redirects]]
  from = "/s/*"
  to = "/.netlify/functions/share/:splat"
  status = 200
  force = true

# Ensure success page isn't cached aggressively while iterating
[[headers]]
  for = "/success.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
